engines:
  duplications:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    config:
      languages:
        JavaScript: true
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
exclude_paths:
  - "server/test/**/*"
  - "client/test/**/*"