sudo: required
dist: trusty
language: node_js
node_js:
  - 6
services:
  - postgresql

before_script:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage